export const templateSeeds = [
  {
    id: 't1-hero-drift',
    name: 'Hero Drift',
    category: 'minimal-hero',
    supportedRatios: ['9:16', '16:9', '1:1'],
    minScreens: 1,
    maxScreens: 3,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'heroScreenshot',
          enabled: true,
          durationInFrames: 120,
          assetIndex: 0,
          motion: 'drift',
          intensity: 0.7,
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#6C5CE7',
    },
  },
  {
    id: 't2-hero-copy',
    name: 'Hero Copy',
    category: 'minimal-hero',
    supportedRatios: ['9:16', '16:9', '1:1'],
    minScreens: 1,
    maxScreens: 2,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'heroScreenshot',
          enabled: true,
          durationInFrames: 150,
          assetIndex: 0,
          motion: 'copy',
          intensity: 0.5,
        },
      ],
      bgStyle: 'solid',
      primaryColor: '#2D3748',
    },
  },
  {
    id: 't3-hero-zoomcut',
    name: 'Hero ZoomCut',
    category: 'minimal-hero',
    supportedRatios: ['9:16', '16:9', '1:1'],
    minScreens: 2,
    maxScreens: 4,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 90,
          assetIndex: 0,
        },
        {
          type: 'heroScreenshot',
          enabled: true,
          durationInFrames: 120,
          assetIndex: 1,
          motion: 'drift',
          intensity: 0.6,
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#667EEA',
    },
  },
  {
    id: 't4-smooth-carousel',
    name: 'Smooth Carousel',
    category: 'landing-showcase',
    supportedRatios: ['9:16', '16:9'],
    minScreens: 3,
    maxScreens: 8,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'carousel',
          enabled: true,
          durationInFrames: 240,
          assetIndices: [0, 1, 2],
          transitionStyle: 'smooth',
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#F687B3',
    },
  },
  {
    id: 't5-stack-reveal',
    name: 'Stack Reveal',
    category: 'landing-showcase',
    supportedRatios: ['9:16', '16:9', '1:1'],
    minScreens: 3,
    maxScreens: 6,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'heroScreenshot',
          enabled: true,
          durationInFrames: 60,
          assetIndex: 0,
          motion: 'drift',
          intensity: 0.8,
        },
        {
          type: 'carousel',
          enabled: true,
          durationInFrames: 180,
          assetIndices: [1, 2, 3],
          transitionStyle: 'stack',
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#4299E1',
    },
  },
  {
    id: 't6-split-showcase',
    name: 'Split Showcase',
    category: 'landing-showcase',
    supportedRatios: ['16:9', '1:1'],
    minScreens: 4,
    maxScreens: 8,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'splitShowcase',
          enabled: true,
          durationInFrames: 200,
          assetIndices: [0, 1, 2, 3],
        },
      ],
      bgStyle: 'solid',
      primaryColor: '#1A202C',
    },
  },
  {
    id: 't7-logo-hero',
    name: 'Logo → Hero',
    category: 'brand-product',
    supportedRatios: ['9:16', '16:9', '1:1'],
    minScreens: 1,
    maxScreens: 3,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'logoIntro',
          enabled: true,
          durationInFrames: 60,
          logoAssetIndex: 0,
        },
        {
          type: 'heroScreenshot',
          enabled: true,
          durationInFrames: 150,
          assetIndex: 0,
          motion: 'drift',
          intensity: 0.6,
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#805AD5',
    },
  },
  {
    id: 't8-brand-carousel',
    name: 'Brand Carousel',
    category: 'brand-product',
    supportedRatios: ['9:16', '16:9'],
    minScreens: 4,
    maxScreens: 10,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'logoIntro',
          enabled: true,
          durationInFrames: 45,
          logoAssetIndex: 0,
        },
        {
          type: 'carousel',
          enabled: true,
          durationInFrames: 240,
          assetIndices: [0, 1, 2, 3],
          transitionStyle: 'smooth',
        },
        {
          type: 'endCard',
          enabled: true,
          durationInFrames: 60,
          logoAssetIndex: 0,
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#ED64A6',
    },
  },
  {
    id: 't9-clean-endcard',
    name: 'Clean End Card',
    category: 'brand-product',
    supportedRatios: ['9:16', '16:9', '1:1'],
    minScreens: 2,
    maxScreens: 5,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'carousel',
          enabled: true,
          durationInFrames: 180,
          assetIndices: [0, 1],
          transitionStyle: 'smooth',
        },
        {
          type: 'endCard',
          enabled: true,
          durationInFrames: 75,
          logoAssetIndex: 0,
        },
      ],
      bgStyle: 'solid',
      primaryColor: '#2D3748',
    },
  },
  {
    id: 't10-7sec-reel',
    name: '7-Second Reel',
    category: 'fast-reels',
    supportedRatios: ['9:16'],
    minScreens: 3,
    maxScreens: 5,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 36,
          assetIndex: 0,
        },
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 36,
          assetIndex: 1,
        },
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 36,
          assetIndex: 2,
        },
        {
          type: 'heroScreenshot',
          enabled: true,
          durationInFrames: 102,
          assetIndex: 3,
          motion: 'drift',
          intensity: 0.9,
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#F56565',
    },
  },
  {
    id: 't11-feature-beats',
    name: 'Feature Beats',
    category: 'fast-reels',
    supportedRatios: ['9:16', '1:1'],
    minScreens: 4,
    maxScreens: 8,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 30,
          assetIndex: 0,
        },
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 30,
          assetIndex: 1,
        },
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 30,
          assetIndex: 2,
        },
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 30,
          assetIndex: 3,
        },
      ],
      bgStyle: 'solid',
      primaryColor: '#1A202C',
    },
  },
  {
    id: 't12-dark-premium',
    name: 'Dark Premium',
    category: 'fast-reels',
    supportedRatios: ['16:9', '1:1'],
    minScreens: 3,
    maxScreens: 6,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'logoIntro',
          enabled: true,
          durationInFrames: 45,
          logoAssetIndex: 0,
        },
        {
          type: 'splitShowcase',
          enabled: true,
          durationInFrames: 180,
          assetIndices: [0, 1, 2],
        },
        {
          type: 'endCard',
          enabled: true,
          durationInFrames: 60,
          logoAssetIndex: 0,
        },
      ],
      bgStyle: 'solid',
      primaryColor: '#000000',
    },
  },
];
