export const templateSeeds = [
  {
    id: 't1-hero-drift',
    name: 'Hero Drift',
    category: 'minimal-hero',
    supportedRatios: ['9:16', '16:9', '1:1'],
    minScreens: 1,
    maxScreens: 3,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'heroScreenshot',
          enabled: true,
          durationInFrames: 120,
          assetIndex: 0,
          motion: 'drift',
          intensity: 0.7,
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#6C5CE7',
    },
  },
  {
    id: 't2-hero-copy',
    name: 'Hero Copy',
    category: 'minimal-hero',
    supportedRatios: ['9:16', '16:9', '1:1'],
    minScreens: 1,
    maxScreens: 2,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'heroScreenshot',
          enabled: true,
          durationInFrames: 150,
          assetIndex: 0,
          motion: 'copy',
          intensity: 0.5,
        },
      ],
      bgStyle: 'solid',
      primaryColor: '#2D3748',
    },
  },
  {
    id: 't3-hero-zoomcut',
    name: 'Hero ZoomCut',
    category: 'minimal-hero',
    supportedRatios: ['9:16', '16:9', '1:1'],
    minScreens: 2,
    maxScreens: 4,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 90,
          assetIndex: 0,
        },
        {
          type: 'heroScreenshot',
          enabled: true,
          durationInFrames: 120,
          assetIndex: 1,
          motion: 'drift',
          intensity: 0.6,
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#667EEA',
    },
  },
  {
    id: 't4-smooth-carousel',
    name: 'Smooth Carousel',
    category: 'landing-showcase',
    supportedRatios: ['9:16', '16:9'],
    minScreens: 3,
    maxScreens: 8,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'carousel',
          enabled: true,
          durationInFrames: 240,
          assetIndices: [0, 1, 2],
          transitionStyle: 'smooth',
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#F687B3',
    },
  },
  {
    id: 't5-stack-reveal',
    name: 'Stack Reveal',
    category: 'landing-showcase',
    supportedRatios: ['9:16', '16:9', '1:1'],
    minScreens: 3,
    maxScreens: 6,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'heroScreenshot',
          enabled: true,
          durationInFrames: 60,
          assetIndex: 0,
          motion: 'drift',
          intensity: 0.8,
        },
        {
          type: 'carousel',
          enabled: true,
          durationInFrames: 180,
          assetIndices: [1, 2, 3],
          transitionStyle: 'stack',
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#4299E1',
    },
  },
  {
    id: 't6-split-showcase',
    name: 'Split Showcase',
    category: 'landing-showcase',
    supportedRatios: ['16:9', '1:1'],
    minScreens: 4,
    maxScreens: 8,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'splitShowcase',
          enabled: true,
          durationInFrames: 200,
          assetIndices: [0, 1, 2, 3],
        },
      ],
      bgStyle: 'solid',
      primaryColor: '#1A202C',
    },
  },
  {
    id: 't7-logo-hero',
    name: 'Logo → Hero',
    category: 'brand-product',
    supportedRatios: ['9:16', '16:9', '1:1'],
    minScreens: 1,
    maxScreens: 3,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'logoIntro',
          enabled: true,
          durationInFrames: 60,
          logoAssetIndex: 0,
        },
        {
          type: 'heroScreenshot',
          enabled: true,
          durationInFrames: 150,
          assetIndex: 0,
          motion: 'drift',
          intensity: 0.6,
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#805AD5',
    },
  },
  {
    id: 't8-brand-carousel',
    name: 'Brand Carousel',
    category: 'brand-product',
    supportedRatios: ['9:16', '16:9'],
    minScreens: 4,
    maxScreens: 10,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'logoIntro',
          enabled: true,
          durationInFrames: 45,
          logoAssetIndex: 0,
        },
        {
          type: 'carousel',
          enabled: true,
          durationInFrames: 240,
          assetIndices: [0, 1, 2, 3],
          transitionStyle: 'smooth',
        },
        {
          type: 'endCard',
          enabled: true,
          durationInFrames: 60,
          logoAssetIndex: 0,
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#ED64A6',
    },
  },
  {
    id: 't9-clean-endcard',
    name: 'Clean End Card',
    category: 'brand-product',
    supportedRatios: ['9:16', '16:9', '1:1'],
    minScreens: 2,
    maxScreens: 5,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'carousel',
          enabled: true,
          durationInFrames: 180,
          assetIndices: [0, 1],
          transitionStyle: 'smooth',
        },
        {
          type: 'endCard',
          enabled: true,
          durationInFrames: 75,
          logoAssetIndex: 0,
        },
      ],
      bgStyle: 'solid',
      primaryColor: '#2D3748',
    },
  },
  {
    id: 't10-7sec-reel',
    name: '7-Second Reel',
    category: 'fast-reels',
    supportedRatios: ['9:16'],
    minScreens: 3,
    maxScreens: 5,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 36,
          assetIndex: 0,
        },
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 36,
          assetIndex: 1,
        },
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 36,
          assetIndex: 2,
        },
        {
          type: 'heroScreenshot',
          enabled: true,
          durationInFrames: 102,
          assetIndex: 3,
          motion: 'drift',
          intensity: 0.9,
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#F56565',
    },
  },
  {
    id: 't11-feature-beats',
    name: 'Feature Beats',
    category: 'fast-reels',
    supportedRatios: ['9:16', '1:1'],
    minScreens: 4,
    maxScreens: 8,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 30,
          assetIndex: 0,
        },
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 30,
          assetIndex: 1,
        },
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 30,
          assetIndex: 2,
        },
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 30,
          assetIndex: 3,
        },
      ],
      bgStyle: 'solid',
      primaryColor: '#1A202C',
    },
  },
  {
    id: 't12-dark-premium',
    name: 'Dark Premium',
    category: 'fast-reels',
    supportedRatios: ['16:9', '1:1'],
    minScreens: 3,
    maxScreens: 6,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'logoIntro',
          enabled: true,
          durationInFrames: 45,
          logoAssetIndex: 0,
        },
        {
          type: 'splitShowcase',
          enabled: true,
          durationInFrames: 180,
          assetIndices: [0, 1, 2],
        },
        {
          type: 'endCard',
          enabled: true,
          durationInFrames: 60,
          logoAssetIndex: 0,
        },
      ],
      bgStyle: 'solid',
      primaryColor: '#000000',
    },
  },
  {
    id: 't13-tech-launch',
    name: 'Tech Startup Launch',
    category: 'tech-showcase',
    supportedRatios: ['16:9', '1:1'],
    minScreens: 2,
    maxScreens: 5,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'animatedBackground',
          enabled: true,
          durationInFrames: 300,
          bgStyle: 'gradient',
        },
        {
          type: 'textReveal',
          enabled: true,
          durationInFrames: 90,
          text: 'Introducing',
          textStyle: 'fadeSlide',
          startFrame: 15,
        },
        {
          type: 'glowingCard',
          enabled: true,
          durationInFrames: 150,
          assetIndex: 0,
          intensity: 0.8,
        },
        {
          type: 'productDemo',
          enabled: true,
          durationInFrames: 180,
          assetIndices: [0, 1, 2],
          headline: 'Build Faster',
          tagline: 'Ship products in days, not months',
          showCursor: true,
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#00D4FF',
    },
  },
  {
    id: 't14-saas-features',
    name: 'SaaS Feature Showcase',
    category: 'tech-showcase',
    supportedRatios: ['16:9', '9:16'],
    minScreens: 3,
    maxScreens: 6,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'animatedBackground',
          enabled: true,
          durationInFrames: 240,
          bgStyle: 'particles',
        },
        {
          type: 'textReveal',
          enabled: true,
          durationInFrames: 60,
          text: 'Powerful Features',
          textStyle: 'scale',
        },
        {
          type: 'featureHighlight',
          enabled: true,
          durationInFrames: 150,
          features: [
            { title: 'Real-time Sync', description: 'Instant updates across all devices', icon: '⚡' },
            { title: 'Advanced Analytics', description: 'Deep insights into your data', icon: '📊' },
            { title: 'Team Collaboration', description: 'Work together seamlessly', icon: '👥' },
          ],
          staggerDelay: 15,
        },
        {
          type: 'glowingCard',
          enabled: true,
          durationInFrames: 90,
          assetIndex: 0,
          intensity: 0.6,
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#7C3AED',
    },
  },
  {
    id: 't15-product-demo',
    name: 'Product Demo Reel',
    category: 'tech-showcase',
    supportedRatios: ['16:9'],
    minScreens: 2,
    maxScreens: 4,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'productDemo',
          enabled: true,
          durationInFrames: 240,
          assetIndices: [0, 1],
          headline: 'See It In Action',
          tagline: 'Watch how easy it is to get started',
          showCursor: true,
        },
        {
          type: 'featureHighlight',
          enabled: true,
          durationInFrames: 120,
          features: [
            { title: 'Simple Setup', icon: '🚀' },
            { title: 'Intuitive UI', icon: '✨' },
            { title: 'Fast Results', icon: '⚡' },
          ],
          staggerDelay: 12,
        },
      ],
      bgStyle: 'solid',
      primaryColor: '#10B981',
    },
  },
  {
    id: 't16-api-docs',
    name: 'API Documentation Preview',
    category: 'tech-showcase',
    supportedRatios: ['16:9', '1:1'],
    minScreens: 1,
    maxScreens: 3,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'animatedBackground',
          enabled: true,
          durationInFrames: 200,
          bgStyle: 'grid',
        },
        {
          type: 'textReveal',
          enabled: true,
          durationInFrames: 60,
          text: 'Simple API',
          textStyle: 'typewriter',
        },
        {
          type: 'glowingCard',
          enabled: true,
          durationInFrames: 180,
          assetIndex: 0,
          title: 'RESTful & GraphQL',
          intensity: 0.7,
        },
        {
          type: 'featureHighlight',
          enabled: true,
          durationInFrames: 100,
          features: [
            { title: 'Well Documented', icon: '📖' },
            { title: 'Type Safe', icon: '🔒' },
          ],
          staggerDelay: 10,
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#F59E0B',
    },
  },
  {
    id: 't17-dev-tool',
    name: 'Developer Tool Promo',
    category: 'tech-showcase',
    supportedRatios: ['16:9', '9:16'],
    minScreens: 2,
    maxScreens: 6,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'animatedBackground',
          enabled: true,
          durationInFrames: 150,
          bgStyle: 'waves',
        },
        {
          type: 'textReveal',
          enabled: true,
          durationInFrames: 50,
          text: 'For Developers',
          textStyle: 'fadeSlide',
        },
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 40,
          assetIndex: 0,
        },
        {
          type: 'zoomCut',
          enabled: true,
          durationInFrames: 40,
          assetIndex: 1,
        },
        {
          type: 'glowingCard',
          enabled: true,
          durationInFrames: 100,
          assetIndex: 2,
          title: 'Boost Your Workflow',
          intensity: 0.9,
        },
        {
          type: 'featureHighlight',
          enabled: true,
          durationInFrames: 80,
          features: [
            { title: 'VS Code Extension', icon: '💻' },
            { title: 'CLI Tools', icon: '⌨️' },
          ],
          staggerDelay: 8,
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#EC4899',
    },
  },
  {
    id: 't18-saas-launch',
    name: 'SaaS Product Launch',
    category: 'saas-production',
    supportedRatios: ['16:9', '9:16', '1:1'],
    minScreens: 2,
    maxScreens: 5,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'animatedBackground',
          enabled: true,
          durationInFrames: 180,
          bgStyle: 'gradient',
        },
        {
          type: 'kineticText',
          enabled: true,
          durationInFrames: 90,
          text: 'Tired of slow workflows?',
          animationType: 'fadeUp',
          highlightWords: ['slow'],
          highlightColor: '#FF6B6B',
          delayPerChar: 3,
          staggerStart: 10,
        },
        {
          type: 'kineticText',
          enabled: true,
          durationInFrames: 90,
          text: 'We built the solution.',
          animationType: 'wave',
          highlightWords: ['solution'],
          delayPerChar: 3,
          staggerStart: 5,
        },
        {
          type: 'glowingCard',
          enabled: true,
          durationInFrames: 150,
          assetIndex: 0,
          intensity: 0.9,
        },
        {
          type: 'featureHighlight',
          enabled: true,
          durationInFrames: 120,
          features: [
            { title: '10x Faster', description: 'Automate your workflow', icon: '⚡' },
            { title: 'Team Sync', description: 'Collaborate in real-time', icon: '👥' },
          ],
          staggerDelay: 12,
        },
        {
          type: 'ctaButton',
          enabled: true,
          durationInFrames: 60,
          ctaText: 'Start Free Trial',
          ctaStyle: 'glow',
        },
        {
          type: 'endCard',
          enabled: true,
          durationInFrames: 90,
          logoAssetIndex: 0,
          text: 'Ready to transform your workflow?',
          tagline: 'Join 10,000+ teams already using us',
          ctaText: 'Get Started Free',
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#6C5CE7',
    },
  },
  {
    id: 't19-device-showcase',
    name: 'Cross-Platform Showcase',
    category: 'saas-production',
    supportedRatios: ['16:9', '1:1'],
    minScreens: 2,
    maxScreens: 4,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'animatedBackground',
          enabled: true,
          durationInFrames: 120,
          bgStyle: 'particles',
        },
        {
          type: 'kineticText',
          enabled: true,
          durationInFrames: 60,
          text: 'Works everywhere',
          animationType: 'scale',
          delayPerChar: 2,
        },
        {
          type: 'deviceFrame',
          enabled: true,
          durationInFrames: 120,
          assetIndex: 0,
          deviceType: 'browser',
        },
        {
          type: 'deviceFrame',
          enabled: true,
          durationInFrames: 100,
          assetIndex: 1,
          deviceType: 'phone',
        },
        {
          type: 'deviceFrame',
          enabled: true,
          durationInFrames: 100,
          assetIndex: 2,
          deviceType: 'laptop',
        },
        {
          type: 'ctaButton',
          enabled: true,
          durationInFrames: 60,
          ctaText: 'Try on Any Device',
          ctaStyle: 'solid',
        },
        {
          type: 'endCard',
          enabled: true,
          durationInFrames: 90,
          logoAssetIndex: 0,
          text: 'One platform, all devices',
          ctaText: 'Start Now',
        },
      ],
      bgStyle: 'solid',
      primaryColor: '#00D4FF',
    },
  },
  {
    id: 't20-cta-focused',
    name: 'Conversion Optimized',
    category: 'saas-production',
    supportedRatios: ['9:16', '1:1'],
    minScreens: 1,
    maxScreens: 3,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'animatedBackground',
          enabled: true,
          durationInFrames: 100,
          bgStyle: 'gradient',
        },
        {
          type: 'kineticText',
          enabled: true,
          durationInFrames: 80,
          text: 'The tool you have been waiting for',
          animationType: 'bounce',
          highlightWords: ['waiting'],
          delayPerChar: 2,
        },
        {
          type: 'glowingCard',
          enabled: true,
          durationInFrames: 100,
          assetIndex: 0,
          intensity: 1,
        },
        {
          type: 'ctaButton',
          enabled: true,
          durationInFrames: 80,
          ctaText: 'Claim Your Free Account',
          ctaStyle: 'glow',
        },
        {
          type: 'featureHighlight',
          enabled: true,
          durationInFrames: 80,
          features: [
            { title: 'No credit card', icon: '✓' },
            { title: '14-day trial', icon: '✓' },
            { title: 'Cancel anytime', icon: '✓' },
          ],
          staggerDelay: 8,
        },
        {
          type: 'endCard',
          enabled: true,
          durationInFrames: 90,
          logoAssetIndex: 0,
          text: 'Join 50,000+ happy users',
          ctaText: 'Get Started Free',
          ctaColor: '#10B981',
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#10B981',
    },
  },
  {
    id: 't21-feature-grid',
    name: 'Feature Grid Showcase',
    category: 'saas-production',
    supportedRatios: ['16:9', '1:1'],
    minScreens: 1,
    maxScreens: 4,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'animatedBackground',
          enabled: true,
          durationInFrames: 80,
          bgStyle: 'grid',
        },
        {
          type: 'kineticText',
          enabled: true,
          durationInFrames: 60,
          text: 'Powerful Features',
          animationType: 'fadeUp',
          delayPerChar: 2,
        },
        {
          type: 'featureHighlight',
          enabled: true,
          durationInFrames: 180,
          features: [
            { title: 'Real-time Analytics', description: 'Track every metric that matters', icon: '📊' },
            { title: 'Team Collaboration', description: 'Work together seamlessly', icon: '👥' },
            { title: 'Automated Workflows', description: 'Save hours every week', icon: '⚡' },
            { title: 'Secure & Compliant', description: 'Enterprise-grade security', icon: '🔒' },
          ],
          staggerDelay: 15,
        },
        {
          type: 'glowingCard',
          enabled: true,
          durationInFrames: 100,
          assetIndex: 0,
          intensity: 0.7,
        },
        {
          type: 'ctaButton',
          enabled: true,
          durationInFrames: 60,
          ctaText: 'See All Features',
          ctaStyle: 'outline',
        },
        {
          type: 'endCard',
          enabled: true,
          durationInFrames: 90,
          logoAssetIndex: 0,
          text: 'Built for modern teams',
          tagline: 'Everything you need in one place',
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#7C3AED',
    },
  },
  {
    id: 't22-onboarding',
    name: 'User Onboarding',
    category: 'saas-production',
    supportedRatios: ['16:9', '9:16'],
    minScreens: 2,
    maxScreens: 5,
    schemaVersion: '1.0.0',
    defaultConfigJson: {
      scenes: [
        {
          type: 'animatedBackground',
          enabled: true,
          durationInFrames: 100,
          bgStyle: 'waves',
        },
        {
          type: 'kineticText',
          enabled: true,
          durationInFrames: 80,
          text: 'Welcome aboard!',
          animationType: 'bounce',
          highlightWords: ['Welcome'],
          delayPerChar: 3,
        },
        {
          type: 'kineticText',
          enabled: true,
          durationInFrames: 60,
          text: 'Let\'s get you started',
          animationType: 'fadeUp',
          delayPerChar: 2,
        },
        {
          type: 'productDemo',
          enabled: true,
          durationInFrames: 200,
          assetIndices: [0, 1],
          headline: 'Quick Setup',
          tagline: 'Get running in under 5 minutes',
          showCursor: true,
        },
        {
          type: 'featureHighlight',
          enabled: true,
          durationInFrames: 100,
          features: [
            { title: 'Step 1: Connect', description: 'Link your tools', icon: '1' },
            { title: 'Step 2: Configure', description: 'Set preferences', icon: '2' },
            { title: 'Step 3: Launch', description: 'Start automating', icon: '3' },
          ],
          staggerDelay: 12,
        },
        {
          type: 'ctaButton',
          enabled: true,
          durationInFrames: 60,
          ctaText: 'Start Setup',
          ctaStyle: 'solid',
        },
        {
          type: 'endCard',
          enabled: true,
          durationInFrames: 90,
          logoAssetIndex: 0,
          text: 'You\'re all set!',
          tagline: 'Questions? We\'re here to help',
          ctaText: 'Go to Dashboard',
        },
      ],
      bgStyle: 'gradient',
      primaryColor: '#F59E0B',
    },
  },
];
